# Site settings
title: Jayden Windle
header-img: img/home-bg-min.jpg
email: jaydenwindle@gmail.com
copyright_name: Jayden Windle
description: "The personal website, portfolio and blog of Jayden Windle."
baseurl: ""
url: "http://jaydenwindle.com"
twitter_username: jayden_windle
github_username:  jaydenwindle
facebook_username:
email_username:  jaydenwindle@gmail.com

# Build settings
markdown: kramdown
highlighter: rouge
permalink: pretty
paginate: 5
exclude: ["less","node_modules","Gruntfile.js","package.json","README.md"]

gems: [jekyll-paginate, jekyll-feed]

# Plugin settings
paginate_path: "/blog/page:num/"
